### ISSUE TITLE
Peer to Peer code review

### ISSUE THREAD

**Issue by Strangeal** [AdnanOlarmmi/Technopreneur#2]
Please maintain the semantic `HTML` best practice. Nest all elements that are not part of the `header` or `footer` inside of the `main` elements.
https://github.com/AdnanOlarmmi/Technopreneur/blob/33d4253aae36d4dfca5fe1c9fac515811c0715ca/index.html#L119-L162

**Comment by AdnanOlarmmi** [comment]
Thank you Justice, 👍 
Looked into that 😃 🤗
